#release configuration
#Tue Oct 02 15:50:53 ALMT 2018
project.scm.com.epam.spring\:learnPharDemo.tag=HEAD
project.rel.com.epam.spring\:learnPharDemoWeb=0.0.1
scm.commentPrefix=[maven-release-plugin] 
pushChanges=true
project.dev.com.epam.spring\:learnPharDemData=0.0.2-SNAPSHOT
project.rel.com.epam.spring\:learnPharDemData=0.0.1
scm.tag=0.0.1
remoteTagging=true
projectVersionPolicyId=default
scm.url=scm\:git\:https\://github.com/akarys191/learnPharDemo.git
scm.tagNameFormat=@{project.artifactId}-@{project.version}
preparationGoals=clean verify
project.scm.com.epam.spring\:learnPharDemoWeb.empty=true
project.rel.com.epam.spring\:learnPharDemo=0.0.1
exec.snapshotReleasePluginAllowed=false
project.scm.com.epam.spring\:learnPharDemo.developerConnection=scm\:git\:https\://github.com/akarys191/learnPharDemo.git
project.scm.com.epam.spring\:learnPharDemData.empty=true
project.dev.com.epam.spring\:learnPharDemoWeb=0.0.2-SNAPSHOT
completedPhase=end-release
project.dev.com.epam.spring\:learnPharDemo=0.0.2-SNAPSHOT
