welcome.message=Hello Mkyong AAA
privateInstance.age=20
# Internationalization
spring.messages.basename=messages/messages
spring.h2.console.enabled=true
spring.profiles.active=springdatajpa


## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://localhost:5432/pharmDemoDb
spring.datasource.username= postgres
spring.datasource.password=Mus@19911004

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update